"""
MCP server integration tests. Requires server running at http://localhost:8000.

    ./.venv/bin/python main.py stdio &
    uv run pytest test_mcp_server.py -v
"""
import json
import os
import sys
import pytest
from dotenv import load_dotenv
load_dotenv()

from mcp.client.stdio import stdio_client, StdioServerParameters
from mcp.client.session import ClientSession
from starlette.testclient import TestClient
from main import mcp

requires_twitter = pytest.mark.skipif(
    not os.getenv("TWITTER_BEARER_TOKEN"),
    reason="TWITTER_BEARER_TOKEN not set",
)

TOOL_NAMES = {
    "fetch_brand_sentiment", "fetch_content_trends",
    "fetch_search_presence", "render_dashboard",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

@pytest.fixture
def client():
    return TestClient(mcp.http_app(transport="streamable-http"))


def _parse(result) -> list | dict:
    raw = result.content[0].text if hasattr(result.content[0], "text") else str(result.content[0])
    return json.loads(raw)


async def _call(tool: str, args: dict):
    server_params = StdioServerParameters(
        command=sys.executable,
        args=["main.py", "stdio"],
    )
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            return await session.call_tool(tool, args)


# ---------------------------------------------------------------------------
# Server / tool discovery
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_server_connects():
    server_params = StdioServerParameters(
        command=sys.executable,
        args=["main.py", "stdio"],
    )
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            tools = await session.list_tools()
    names = {t.name for t in tools.tools}
    assert TOOL_NAMES.issubset(names), f"Missing tools: {TOOL_NAMES - names}"


# ---------------------------------------------------------------------------
# render_dashboard
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_render_basic_dashboard():
    data = _parse(await _call("render_dashboard", {
        "title": "Test Dashboard",
        "summary": "This is a summary generated by pytest.",
        "cards": [{"title": "T", "url": "https://example.com", "points": 10, "source": "hn", "ai_summary": "S."}],
    }))
    assert data.get("status") == "dashboard_ready"


@pytest.mark.asyncio
async def test_render_with_bar_chart():
    data = _parse(await _call("render_dashboard", {
        "title": "Bar Chart Test",
        "summary": "Testing bar chart rendering.",
        "chart": {"type": "bar", "title": "Pts", "labels": ["HN", "Dev"], "values": [120, 80]},
    }))
    assert data.get("status") == "dashboard_ready"


@pytest.mark.asyncio
async def test_render_with_pie_chart():
    data = _parse(await _call("render_dashboard", {
        "title": "Pie Chart Test",
        "summary": "Testing pie chart rendering.",
        "chart": {"type": "pie", "title": "Dist", "labels": ["HN", "Dev"], "values": [60, 40]},
    }))
    assert data.get("status") == "dashboard_ready"


@pytest.mark.asyncio
async def test_render_with_radar_chart():
    data = _parse(await _call("render_dashboard", {
        "title": "Radar Chart Test",
        "summary": "Testing radar chart rendering.",
        "chart": {
            "type": "radar",
            "title": "Metrics",
            "data": [{"label": "Speed", "val": 80}, {"label": "Safety", "val": 90}],
            "series": [{"dataKey": "val", "label": "Score"}],
        },
    }))
    assert data.get("status") == "dashboard_ready"


@pytest.mark.asyncio
async def test_render_empty_cards():
    data = _parse(await _call("render_dashboard", {
        "title": "Empty Dashboard",
        "summary": "No articles found.",
        "cards": []
    }))
    assert data.get("status") == "dashboard_ready"


@pytest.mark.asyncio
async def test_render_with_metrics():
    data = _parse(await _call("render_dashboard", {
        "title": "Metrics Test",
        "summary": "Testing KPI metrics.",
        "metrics": [
            {"label": "Growth", "value": "15%", "trend": "up", "trendSentiment": "positive"},
            {"label": "Errors", "value": "2", "trend": "down", "trendSentiment": "positive"}
        ]
    }))
    assert data.get("status") == "dashboard_ready"


# ---------------------------------------------------------------------------
# fetch_brand_sentiment
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_brand_sentiment_returns_list():
    data = _parse(await _call("fetch_brand_sentiment", {"brands": ["PharmEasy"], "platforms": "reddit", "timeframe": "w"}))
    assert isinstance(data, list)
    assert len(data) > 0


@pytest.mark.asyncio
async def test_brand_sentiment_structure():
    data = _parse(await _call("fetch_brand_sentiment", {"brands": ["PharmEasy"], "platforms": "reddit", "timeframe": "w"}))
    row = data[0]
    assert "brand" in row
    assert "platform" in row
    assert "sentiment_score" in row or "status" in row


@pytest.mark.asyncio
async def test_brand_sentiment_multiple_brands():
    data = _parse(await _call("fetch_brand_sentiment", {
        "brands": ["PharmEasy", "Apollo"],
        "platforms": ["reddit"],
        "timeframe": "w",
    }))
    assert isinstance(data, list)
    brands_seen = {r["brand"] for r in data if "brand" in r}
    assert len(brands_seen) >= 1


@pytest.mark.asyncio
async def test_brand_sentiment_reddit_and_linkedin():
    data = _parse(await _call("fetch_brand_sentiment", {
        "brands": ["PharmEasy"],
        "platforms": ["reddit", "linkedin"],
        "timeframe": "w",
    }))
    assert isinstance(data, list)
    platforms_seen = {r["platform"] for r in data if "platform" in r}
    assert "reddit" in platforms_seen


@requires_twitter
@pytest.mark.asyncio
async def test_brand_sentiment_twitter():
    data = _parse(await _call("fetch_brand_sentiment", {
        "brands": ["PharmEasy"],
        "platforms": ["twitter"],
        "timeframe": "w",
    }))
    assert isinstance(data, list)
    row = next((r for r in data if r.get("platform") == "twitter"), None)
    assert row is not None
    assert row.get("source") == "twitter_api_v2" or "status" in row

    if row["top_posts"]:
        post = row["top_posts"][0]
        assert "title" in post
        assert "body" in post
        assert "url" in post
        assert "sentiment" in post


@pytest.mark.asyncio
async def test_brand_sentiment_top_posts_shape():
    data = _parse(await _call("fetch_brand_sentiment", {"brands": ["PharmEasy"], "platforms": "reddit", "timeframe": "w"}))
    row = next((r for r in data if r.get("platform") == "reddit" and "top_posts" in r), None)
    if row is None:
        pytest.skip("Reddit unavailable or insufficient data")
    assert isinstance(row["top_posts"], list)
    if row["top_posts"]:
        post = row["top_posts"][0]
        assert "title" in post
        assert "body" in post
        assert "url" in post
        assert "sentiment" in post


# ---------------------------------------------------------------------------
# fetch_content_trends
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_content_trends_returns_list():
    data = _parse(await _call("fetch_content_trends", {"topic": "online pharmacy", "region_tier": "tier1"}))
    assert isinstance(data, list)
    assert len(data) > 0


@pytest.mark.asyncio
async def test_content_trends_structure():
    data = _parse(await _call("fetch_content_trends", {"topic": "medicine delivery"}))
    row = data[0]
    assert "city" in row or "status" in row


@pytest.mark.asyncio
async def test_content_trends_tier_filter():
    data = _parse(await _call("fetch_content_trends", {"topic": "health insurance", "region_tier": "tier1"}))
    real = [r for r in data if "tier" in r]
    if real:
        assert all(r["tier"] == "tier1" for r in real)


@pytest.mark.asyncio
async def test_content_trends_interest_score_range():
    data = _parse(await _call("fetch_content_trends", {"topic": "online pharmacy"}))
    real = [r for r in data if "interest_score" in r]
    for r in real:
        assert 0 <= r["interest_score"] <= 100


@pytest.mark.asyncio
async def test_content_trends_related_queries_list():
    data = _parse(await _call("fetch_content_trends", {"topic": "online pharmacy"}))
    real = [r for r in data if "related_queries" in r]
    if real:
        assert isinstance(real[0]["related_queries"], list)


# ---------------------------------------------------------------------------
# fetch_search_presence
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_search_presence_returns_list():
    data = _parse(await _call("fetch_search_presence", {
        "brands": ["PharmEasy"],
        "keywords": ["buy medicine online india"],
    }))
    assert isinstance(data, list)
    assert len(data) > 0


@pytest.mark.asyncio
async def test_search_presence_structure():
    data = _parse(await _call("fetch_search_presence", {
        "brands": ["PharmEasy"],
        "keywords": ["online pharmacy"],
    }))
    row = data[0]
    assert "keyword" in row
    assert "brand" in row
    assert "present" in row


@pytest.mark.asyncio
async def test_search_presence_multiple_brands_and_keywords():
    data = _parse(await _call("fetch_search_presence", {
        "brands": ["PharmEasy", "Apollo"],
        "keywords": ["online pharmacy india", "order medicines"],
    }))
    assert isinstance(data, list)
    assert len(data) >= 4


@pytest.mark.asyncio
async def test_search_presence_rank_within_bounds():
    data = _parse(await _call("fetch_search_presence", {
        "brands": ["PharmEasy"],
        "keywords": ["online pharmacy"],
    }))
    for row in data:
        if row.get("rank") is not None:
            assert 1 <= row["rank"] <= 10


@pytest.mark.asyncio
async def test_search_presence_top_results_shape():
    data = _parse(await _call("fetch_search_presence", {
        "brands": ["PharmEasy"],
        "keywords": ["buy medicine online india"],
    }))
    row = next((r for r in data if "top_results" in r), None)
    if row is None:
        pytest.skip("DDGS unavailable")
    assert isinstance(row["top_results"], list)
    if row["top_results"]:
        r0 = row["top_results"][0]
        assert "rank" in r0
        assert "url" in r0


# ---------------------------------------------------------------------------
# HTTP Custom Routes
# ---------------------------------------------------------------------------

def test_dashboard_route_dark(client):
    resp = client.get("/dashboard?theme=dark")
    assert resp.status_code == 200
    assert "class=\"dark\"" in resp.text
    assert "No dashboard rendered yet" in resp.text


def test_dashboard_route_light(client):
    resp = client.get("/dashboard?theme=light")
    assert resp.status_code == 200
    assert "class=\"dark\"" not in resp.text
    assert "No dashboard rendered yet" in resp.text
